import {NextResponse} from "next/server";
const API="https://api.sportsgameodds.com/v2";
function dec(n:number){return n>0?n/100+1:100/Math.abs(n)+1}
function calc(a:number[]){const s=a.reduce((x,o)=>x+1/o,0);if(s>=1)return{has:false,p:0,stakes:[] as number[]};return{has:true,p:(1/s-1)*100,stakes:a.map(o=>(100/o)/s)}}
export async function GET(req:Request){const key=process.env.SPORTSGAMEODDS_API_KEY||process.env.SPORTSGAMEODDS_KEY;if(!key)return NextResponse.json({error:"Missing SPORTSGAMEODDS_API_KEY"},{status:500});const u=new URL(req.url);const leagues=(u.searchParams.get("leagues")||"NBA,NFL,NHL").split(",").map(x=>x.trim()).filter(Boolean);const events:any[]=[];
for(const league of leagues){const q=new URL(API+"/events");q.searchParams.set("leagueID",league);q.searchParams.set("finalized","false");q.searchParams.set("oddsAvailable","true");q.searchParams.set("limit","100");const r=await fetch(q,{headers:{"x-api-key":key},cache:"no-store"});if(!r.ok)return NextResponse.json({error:"SportsGameOdds "+r.status+" for "+league},{status:502});const d=await r.json();events.push(...(d.data||[]))}
const out:any[]=[];
for(const e of events){const matchup=(e.teams?.away?.names?.long||"Away")+" @ "+(e.teams?.home?.names?.long||"Home");const m:Record<string,any[]>={};
for(const odd of Object.values(e.odds||{}) as any[]){const t=odd.betTypeID,side=odd.sideID;if(odd.periodID&&odd.periodID!=="game")continue;if(!["sp","ml","ou"].includes(t))continue;for(const [book,b] of Object.entries(odd.byBookmaker||{}) as any){if(b?.available===false||!b?.odds)continue;const n=Number(b.odds);if(!Number.isFinite(n))continue;const line=t==="sp"?b.spread:t==="ou"?b.overUnder:null;const k=t+"|"+side+"|"+String(line??"");(m[k]??=[]).push({bookmaker:book,american:n,decimal:dec(n),line})}}
for(const k of Object.keys(m)){const [t,side,line]=k.split("|");const opposite=side==="home"?"away":side==="over"?"under":null;if(!opposite)continue;const a=m[k],b=m[t+"|"+opposite+"|"+line];if(!b)continue;const aa=a.reduce((x,y)=>y.decimal>x.decimal?y:x),bb=b.reduce((x,y)=>y.decimal>x.decimal?y:x),c=calc([aa.decimal,bb.decimal]);if(c.has)out.push({matchup,market:t==="sp"?"spread":t==="ou"?"total":"moneyline",profitPct:c.p,legs:[{side,bookmaker:aa.bookmaker,odds:aa.american,line:aa.line,stakePct:c.stakes[0]},{side:opposite,bookmaker:bb.bookmaker,odds:bb.american,line:bb.line,stakePct:c.stakes[1]}]})}}
out.sort((a,b)=>b.profitPct-a.profitPct);return NextResponse.json({events:events.length,opportunities:out})}